const countries = [
  {
    id: 1,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/2560px-Flag_of_Germany.svg.png",
    name: "Germany",
    population: "Population:",
    populationText: "81,770,900",
    region: "Region:",
    regionText: "Europe",
    capital: "Capital:",
    capitalText: "Berlin",
  },
  {
    id: 2,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png",
    name: "Spain",
    population: "Population:",
    populationText: "323,947,000",
    region: "Region:",
    regionText: "Europe",
    capital: "Capital: ",
    capitalText: "Madrid",
  },
  {
    id: 3,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/640px-Flag_of_Brazil.svg.png",
    name: "Brazil",
    population: "Population:",
    populationText: "206,135,893",
    region: "Region:",
    regionText: "Americas",
    capital: "Capital:",
    capitalText: "Brasília",
  },
  {
    id: 4,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1024px-Flag_of_Iceland.svg.png",
    name: "Iceland",
    population: "Population:",
    populationText: "334,300",
    region: "Region:",
    regionText: "Europe",
    capital: "Capital:",
    capitalText: "Reykjavík",
  },
  {
    id: 5,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg/1024px-Flag_of_Afghanistan_%282013%E2%80%932021%29.svg.png",
    name: "Afghanistan",
    population: "Population:",
    populationText: "27,657,145",
    region: "Region:",
    regionText: "Asia",
    capital: "Capital:",
    capitalText: "Kabul",
  },
  {
    id: 6,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1280px-Flag_of_Uzbekistan.svg.png",
    name: "Uzbekistan",
    population: "Population:",
    populationText: "35,482,369",
    region: "Region:",
    regionText: "Asia",
    capital: "Capital:",
    capitalText: "Tashkent",
  },
  {
    id: 7,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/2560px-Flag_of_Albania.svg.png",
    name: "Albania",
    population: "Population:",
    populationText: "2,886,026",
    region: "Region:",
    regionText: "Europe",
    capital: "Capital:",
    capitalText: "Tirana",
  },
  {
    id: 8,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/1280px-Flag_of_Algeria.svg.png",
    name: "Algeria",
    population: "Population:",
    populationText: "40,400,000",
    region: "Region:",
    regionText: "Africa",
    capital: "Capital:",
    capitalText: "Algiers",
  },
];

const op = [
  {
    id: 1,
    opText: "All",
    value: "All",
  },
  {
    id: 2,
    opText: "Germany",
    value: "Germany",
  },
  {
    id: 3,
    opText: "Spain",
    value: "Spain",
  },
  {
    id: 4,
    opText: "Brazil",
    value: "Brazil",
  },
  {
    id: 5,
    opText: "Iceland",
    value: "Iceland",
  },
  {
    id: 6,
    opText: "Afghanistan",
    value: "Afghanistan",
  },
  {
    id: 7,
    opText: "Uzbekistan",
    value: "Uzbekistan",
  },
  {
    id: 8,
    opText: "Albania",
    value: "Albania",
  },
  {
    id: 9,
    opText: "Algeria",
    value: "Algeria",
  },
];
